version: '3'
services:
  nodejs:
    image: node:12
    # restart: always
    ports:
      - 8080:8080
    volumes:
      - ./:/root/
    working_dir: /root/
    command: ["node", "start-socket-server.js"]